[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]] #ファイルツリー表示
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]] # alignment
repo = 'junegunn/vim-easy-align'

[[plugins]] # git
repo = 'tpope/vim-fugitive'

[[plugins]] # git（Unite拡張？）
repo = 'kmnk/vim-unite-giti'

[[plugins]] # match
repo = 'tmhedberg/matchit'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # カラースキーマ
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark
  " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
  au MyAutoCmd VimEnter * nested colorscheme hybrid
'''
