[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

[[plugins]] #editorconfigを使用
repo = 'editorconfig/editorconfig-vim'
on_i = 1

[[plugins]] #インデントガイド
repo = 'nathanaelkane/vim-indent-guides'
on_i = 1

[[plugins]] #ejsのシンタックス
repo = 'nikvdp/ejs-syntax'
on_ft = ['ejs']

[[plugins]] #emmetを使用
repo = 'mattn/emmet-vim'
on_ft = ['html','css','scss','ejs']

[[plugins]] #CSS3にシンタックスをあてる
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css','scss']

[[plugins]] #javascropt（要変数設定）
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

[[plugins]] #html5シンタックス？（要変数設定）
repo = 'othree/html5.vim'
on_ft = ['html','ejs']

[[plugins]] #SCSSシンタックス
repo = 'cakebaker/scss-syntax.vim'
on_ft = ['scss']

